---
- name: Ensure certbot directories exists
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /opt/certbot
    - /var/log/certbot
    - "{{ letsencrypt_webroot }}"

- name: Download certbot installer
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /opt/certbot/certbot-auto
    mode: 0755

#- name: Verify if port 80 is serving files
#  command: curl -sf http://{{ letsencrypt_domain }}/.well-known
#  register: http_code
#  ignore_errors: true
  
- name: Generate ceritifacte
  command: "./certbot-auto certonly -n --agree-tos --standalone --email {{ letsencrypt_email }} {{ item }}"
  args:
    chdir: /opt/certbot
  with_items: "{{ letsencrypt_domains }}"

#- name: Generate ceritifacte when port 80 is in use
#  command: "./certbot-auto certonly -n --agree-tos --email {{ letsencrypt_email }} --webroot -w {{ letsencrypt_webroot }} -d {{ letsencrypt_domain }}"
#  args:
#    chdir: /opt/certbot
#  when: http_code == 200 

- name: Enable autorenew every week
  cron:
    name: letsencrypt
    minute: 0
    hour: 1
    weekday: 3
    job: "/opt/certbot/certbot-auto renew --webroot -w {{ letsencrypt_webroot }} --text >> /var/log/letsencrypt/renewal.log && systemctl restart {{ letsencrypt_http_server }}"
  when: letsencrypt_autorenew
